"use strict";
var x;
var y;
var z = "abc";
console.log(typeof (x));
console.log(typeof (y));
console.log(typeof (z));
var something;
console.log("Hello World");
console.log(typeof (something));
//console.log(hello);
//let p:number = "hello";
